test:msrv:
  # Don't forget to update README when changing this!
  image: rust:1.51
  script:
  - cargo version && cargo build --examples && cargo test

test:stable:
  image: rust:latest
  script:
  - cargo version && cargo build --examples && cargo test

test:beta:
  image: rustdocker/rust:beta
  script:
  - cargo version && cargo build --examples && cargo test

test:nightly:
  image: rustdocker/rust:nightly
  script:
  - cargo version && cargo build --examples --all-features && cargo test
