test:msrv:
  # Don't forget to update README when changing this!
  image: rust:1.53
  script:
  # 1.5 changed to an edition the MSRV doesn't work any more
  - cargo update -p 'byteorder' --precise '1.4.3'
  - cargo version && cargo build --examples && cargo test

test:stable:
  image: rust:latest
  script:
  - cargo version && cargo build --examples && cargo test

test:beta:
  image: rustdocker/rust:beta
  script:
  - cargo version && cargo build --examples && cargo test

test:nightly:
  image: rustdocker/rust:nightly
  script:
  - cargo version && cargo build --examples --all-features && cargo test --all-features
  - cd std-embedded-nal-async/ && cargo version && cargo build --examples --all-features && cargo test --all-features
