test:msrv:
  # Don't forget to update README when changing this!
  image: rust:1.53
  script:
  # 1.5 changed to an edition the MSRV doesn't work any more
  - cargo update -p 'byteorder' --precise '1.4.3'
  - cargo version
  - cargo build --examples 
  - cargo test
  # Not testing std-embedded-nal-async: That does not have an MSRV.

test:stable:
  image: rust:latest
  script:
  - cargo version
  - cargo build --examples 
  - cargo test
  - cd std-embedded-nal-async/
  - cargo build --examples --all-features
  - cargo test --all-features

test:beta:
  image: rustdocker/rust:beta
  script:
  - cargo version
  - cargo build --examples 
  - cargo test
  - cd std-embedded-nal-async/
  - cargo build --examples --all-features
  - cargo test --all-features

test:nightly:
  image: rustdocker/rust:nightly
  script:
  - cargo version
  - cargo build --examples 
  - cargo test
  - cd std-embedded-nal-async/
  - cargo build --examples --all-features
  - cargo test --all-features

fmt:
  image: rustdocker/rust:nightly
  script:
  - cargo fmt --check
  - cd std-embedded-nal-async/
  - cargo fmt --check
